accounts:
    message: "Welcome to EazyBank Accounts QA APIs"
    contactDetails:
      name: "Bob Bobson - QA Lead"
      email: "{cipher}AQCwsN/Lb0G8EFXjfCIL3CF1UJG+mfzmOglPCC0fKc71oUOQk7pD+/I+bIQmYCS2NdZV9WWIeM+RsfnbjsGWXdW9WLyMV1XP5OVJ1lCWDdL7zcIUAh+bSmIFEJT95uER8+mp9r1KCcZK7JQdjPiQ4SQneOXnjObbkrhByS6ZPfsofsLt/IvTyPHSDb+XYCK3lkJd18h3DlvRv4udD183sW7YeFx1X6O+0+bNHonlBHZebfiMrCLNBJZ0xvvWaSHJbg7cC4ZiegtnEyzApXUFxyqTA0vo7QqCdM2qTSeBNu+QGfzjq0GOatKLnstPRtEWmPi969+XolF7/V5GXcWprcFOm0PbGfFeX2GBuKq7zFasi+d2hv7YzxXdAcnwehxxLcY="
    onCallSupport:
      - (555) 555-3333
      - (555) 555-4444

build:
  version: "2.0.0"
