server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}&binaryTransfer=true&reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      keepalive-time: 60000
      idle-timeout: 120000
      leak-detection-threshold: 150000
      max-lifetime: 180000
      connection-timeout: 3000
      validation-timeout: 2500
      register-mbeans: true

  jpa:
    # Disables open-in-view sessions which forces the persistence context to stay open so that the view layer can trigger proxy initialization. This will keep the DB connection open for a long time which would have a bad effect on performance.
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.Database.POSTGRESQL
    # DESC: Auto-generate table from entities
    # DESC: This config does the magic of automatically creating tables for you based on the JPA entities you have created
    # generate-ddl: true
    # DESC: So init-data.sql will work
    defer-datasource-initialization: true
    hibernate:
      # DESC: Update schema if necessary (e.g. add new columns, etc.)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      platform: postgres
      schema-locations: classpath:scripts/init-schema.sql
      mode: always

  # DESC: For refreshing configs from config server
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

endpoints:
  shutdown:
    enabled: true

  # DESC: Enable the "/actuator/busrefresh" endpoint
  spring:
    cloud:
      bus:
        refresh:
          enabled: true

# DESC: Actuator endpoint management
management:
  endpoints:
    # DESC: Expose all web actuator endpoints
    web:
      exposure:
        include: '*'

  # DESC: For enabling the "/actuator/info" endpoint
  info:
    env:
      enabled: true

  # DESC: Enables the "actuator/shutdown" endpoint
  endpoint:
    shutdown:
      enabled: true
