cards:
  message: "Welcome to EazyBank Cards Default APIs"
  contactDetails:
    name: "Gary Garrison - Developer"
    email: "{cipher}AQB33sjkltk0pVqEMkJb+fptfHHB0L1keZg5lwEluFUElSKyx7UYN+wt8u2pPtZL7Ua9aeRbNDPckqS1hb2ztb9gJUaut9TPaCzNGv5NBWccr+EPwVwCAH36vFM729Wdfu1pxUmfK4vRBnk6plIZb+Eid+FL6yODO1c6oK9y2e2Wd3JTgzkDX0gaaeEDkvKr0cmWtTs+8ij8hNGD9XecVOUFdzXMhvC710y7uFEcfJu7mtKjyF+8XnEYwhu8rmk9JfL3G2Ekdb2q4TEJ5/YYwmSphxrHMO5OM0cy9/N3E3EKWLQsTEtx3hcm6qF7QsPwenDf3yQCTr8oXTjnzqGVaUOv0eOuFFtuAzrmjnQ2AU785/8B7d5W33Uqdq69B8F3Ym7VipZd+qRc9JPUoO/W1L00"
  onCallSupport:
    - (999) 444-2222
    - (999) 444-3333

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Microservice"
    version: "1.0.0"
