cards:
  message: "Welcome to EazyBank Cards webhook APIs"
  contactDetails:
    name: "Harry Harrison - QA Lead"
    email: "{cipher}AQB2n1bE3pGNwo4615lJmxCrxopI3OboHQjv4iz1mwYXFkxRG/2XZnA6fsAhQFCn8SKR6ZKQr+mAJM+IhOTXyZRyKiTgR/iCL0fkedVhgnDxRdA6vvlEbujwh3xx+dIC5UiImUdv2zVGb9Tn5dxHX5LeMFZQTKS60HP/ZHq/ItDcLM2x4FgtwpxnDe3zXXSy1TyJ1Dmx4djZzfTMDKAh6rbMfi9db3deKfzD1JJblmZBvC7NY2x/jD4eRIcaMmFdkK2kLLSxCkh3V5bVmMxe622/EMNsXZzB/y2249z5zHKZcZXokLlMs4BptzPodbsoUoiv/rl4VCP2P+HkfXfg3RvQd68OadRVLpzk7dcEG8YE2bXteNQdTlwcU4s+I9GT7tbPWtiYYfV/iutMEZDj8tUE"
  onCallSupport:
    - (999) 444-6666
    - (999) 444-7777
