loans:
  message: "Welcome to EazyBank Loans QA APIs"
  contactDetails:
    name: "Emma Emmerson - QA Lead"
    email: "{cipher}AQADqTNawOxG87tBcrwbHkSC0wAx5XzMKfYy0llAapDzvPVMps4d1Z0K0AoYNnpiOVgTjrcJC53hwQ11q5Ffo2RqQvC0CBP/cBlgu4w2Bc4Sl1S7WKwaA0EwozRCpzJQT7/jSTrVaXAm9CXXp29gxyLDcaX3f04Z0TVKLDXeDAUHDMAVCRLgLgatnwyPea1yD6AL9D7AY2p8zQLSw9wohRszXaiDchRiWlQHPNjhmSvRsvVTK975sZUeXiQZw4N/OCt5boevEchllMgBk3bmjdekNwdZ4BrV6TSvf3ODkh4WMklvDVEdborUqW0dCDtqNl2SzHd3t1t3BLIdzCOP+ObdEBiQiiT6Z8k/sIeR3eE+TbLg9udC+86iolvJGU3HPViWl/ljmY6mJMYUAj3UsGGi"
  onCallSupport:
    - (666) 111-3333
    - (666) 111-4444
